#include <iostream>
#include <cassert>
#include <exception>
#include "../src/collatz/CollatzMap.h"
#include "../src/collatz/CollatzVector.h"
#include "../src/collatz/CollatzMultiThread.h"

using namespace collatz;

void test_collatz_map() {
    CollatzMap solver;
    CollatzResult result = solver.find_longest_chain(10);
    // For limit 10, longest chain is generated by 9, taking 19 steps.
    assert(result.starting_number == 9);
    assert(result.steps == 19);
    std::cout << "[PASS] CollatzMap tests\n";
}

void test_collatz_vector() {
    CollatzVector solver(100);
    CollatzResult result = solver.find_longest_chain(10);
    assert(result.starting_number == 9);
    assert(result.steps == 19);
    std::cout << "[PASS] CollatzVector tests\n";
}

void test_collatz_multithread() {
    CollatzMultiThread solver(2); // Use 2 threads to test chunking
    CollatzResult result = solver.find_longest_chain(10);
    assert(result.starting_number == 9);
    assert(result.steps == 19);
    std::cout << "[PASS] CollatzMultiThread tests\n";
}

void run_all_tests() {
    try {
        test_collatz_map();
        test_collatz_vector();
        test_collatz_multithread();
        std::cout << "All unit tests passed successfully.\n";
    } catch (const std::exception& e) {
        std::cerr << "[FAIL] Test exception: " << e.what() << "\n";
        exit(1);
    }
}

int main() {
    std::cout << "--- Collatz Analyzer Test Suite ---\n";
    run_all_tests();
    return 0;
}
