#include <iostream>
#include <string>
#include <chrono>
#include <iomanip>
#include <windows.h>

#include "collatz/CollatzMap.h"
#include "collatz/CollatzVector.h"
#include "collatz/CollatzMultiThread.h"
#include "collatz/ReverseTree.h"
#include "collatz/OddToOdd.h"

using namespace collatz;
using namespace std;
using namespace std::chrono;

/**
 * @brief Runs benchmarking suite for Collatz sequence optimizers
 */
void run_benchmark(long long limit) {
    cout << "========================================================\n";
    cout << "Collatz Sequence Optimization Benchmark\n";
    cout << "Search Limit: " << limit << "\n";
    cout << "========================================================\n";

    long long duration_map = -1, duration_vec = -1, duration_mt = -1;

    // --- Benchmark 1: unordered_map ---
    cout << "\n[1] Running unordered_map implementation...\n";
    try {
        CollatzMap map_solver;
        auto start_map = high_resolution_clock::now();
        CollatzResult result_map = map_solver.find_longest_chain(limit);
        auto end_map = high_resolution_clock::now();
        duration_map = duration_cast<milliseconds>(end_map - start_map).count();

        cout << "    Longest sequence generated by : " << result_map.starting_number << "\n";
        cout << "    Total steps                   : " << result_map.steps << "\n";
        cout << "    Global peak value reached     : " << result_map.peak_value << "\n";
        cout << "    Execution time                : " << duration_map << " ms\n";
    } catch (const std::bad_alloc&) {
        cout << "    [ERROR] std::bad_alloc! unordered_map exceeded memory limits.\n";
        cout << "    (This is expected for massive limits on 32-bit processes).\n";
    }

    // --- Benchmark 2: vector ---
    cout << "\n[2] Running vector-based implementation...\n";
    try {
        CollatzVector vector_solver(limit); 
        auto start_vec = high_resolution_clock::now();
        CollatzResult result_vec = vector_solver.find_longest_chain(limit);
        auto end_vec = high_resolution_clock::now();
        duration_vec = duration_cast<milliseconds>(end_vec - start_vec).count();

        cout << "    Longest sequence generated by : " << result_vec.starting_number << "\n";
        cout << "    Total steps                   : " << result_vec.steps << "\n";
        cout << "    Global peak value reached     : " << result_vec.peak_value << "\n";
        cout << "    Execution time                : " << duration_vec << " ms\n";
    } catch (const std::bad_alloc&) {
        cout << "    [ERROR] std::bad_alloc! vector exceeded available memory.\n";
    }
    
    // --- Benchmark 3: Multi-threaded ---
    SYSTEM_INFO sysinfo;
    GetSystemInfo(&sysinfo);
    int num_threads = sysinfo.dwNumberOfProcessors > 0 ? sysinfo.dwNumberOfProcessors : 4;
    cout << "\n[3] Running multi-threaded implementation (" << num_threads << " threads)...\n";
    try {
        CollatzMultiThread mt_solver(num_threads);
        auto start_mt = high_resolution_clock::now();
        CollatzResult result_mt = mt_solver.find_longest_chain(limit);
        auto end_mt = high_resolution_clock::now();
        duration_mt = duration_cast<milliseconds>(end_mt - start_mt).count();

        cout << "    Longest sequence generated by : " << result_mt.starting_number << "\n";
        cout << "    Total steps                   : " << result_mt.steps << "\n";
        cout << "    Global peak value reached     : " << result_mt.peak_value << "\n";
        cout << "    Execution time                : " << duration_mt << " ms\n";
    } catch (const std::bad_alloc&) {
        cout << "    [ERROR] std::bad_alloc! Multi-threaded implementation exceeded available memory.\n";
    }

    // --- Comparison ---
    cout << "\n========================================================\n";
    cout << "Performance Comparison:\n";
    
    if (duration_map >= 0 && duration_vec >= 0) {
        double map_ms = max(1.0, (double)duration_map);
        double vec_ms = max(1.0, (double)duration_vec);
        cout << "Single-threaded Vector was " << fixed << setprecision(2) 
             << (map_ms / vec_ms) << "x faster than Map approach.\n";
    }
    if (duration_vec >= 0 && duration_mt >= 0) {
        double vec_ms = max(1.0, (double)duration_vec);
        double mt_ms = max(1.0, (double)duration_mt);
        cout << "Multi-threaded Vector was  " << fixed << setprecision(2) 
             << (vec_ms / mt_ms) << "x faster than Single-threaded Vector.\n";
    }
    if (duration_map >= 0 && duration_mt >= 0) {
        double map_ms = max(1.0, (double)duration_map);
        double mt_ms = max(1.0, (double)duration_mt);
        cout << "Multi-threaded Vector was  " << fixed << setprecision(2) 
             << (map_ms / mt_ms) << "x faster than Map approach.\n";
    }
    cout << "========================================================\n";
}

int main(int argc, char* argv[]) {
    ios::sync_with_stdio(false);
    cin.tie(NULL);

    long long limit = 1000000;

    // Command line limit parsing with robust error handling
    if (argc > 1) {
        try {
            long long parsed = stoll(argv[1]);
            if (parsed <= 0) {
                throw std::invalid_argument("Limit must be positive.");
            }
            limit = parsed;
        } catch (const std::exception& e) {
            cerr << "[ERROR] Invalid argument: " << e.what() << "\n";
            cerr << "Usage: ./collatz <positive_integer_limit>\n";
            cerr << "Falling back to default limit: 1,000,000\n";
        }
    }

    // 1. Run optimization benchmarks
    run_benchmark(limit);

    // 2. Run Reverse Tree Generation
    int max_depth = 25; 
    ReverseTreeAnalyzer::analyze(max_depth);
    
    // 3. Run Compressed Odd-to-Odd Map Analysis
    OddToOddAnalyzer::analyze(limit);

    return 0;
}
